### ISSUE TITLE
Kái-chò Github Release

### ISSUE THREAD

**Issue by ngoohebi** [i3thuan5/weasel#1]
https://www.appveyor.com/docs/deployment/github/

Sūn-sòa kā goân-pún ê BinTray Deploy the̍h tiāu.
https://github.com/i3thuan5/weasel/blob/master/appveyor.yml

```
deploy:
  - provider: BinTray
    username: lotem
    api_key: &bintray_api_key
      secure: KutsvYFjEDoWMhEKxBP2DlXku/pSVfUsNnG70GFyYQo2vZ8GP0Yzu1rrfvyTEQbTZaJF3gwZ+2+Z5mDXsUSeIouiqzlQjiCKYScuEttLF5w=
    subject: rime
    repo: weasel
    package: release
    version: 0.14.3
    publish: false
    override: false
    explode: false
    on:
      APPVEYOR_REPO_TAG: true
  - provider: BinTray
    username: lotem
    api_key: *bintray_api_key
    subject: rime
    repo: weasel
    package: testing
    version: 0.14.3.$(APPVEYOR_BUILD_NUMBER)
    publish: true
    override: false
    explode: false
    on:
      branch: master
```
